from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 100, 101, 22))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.stateChanged.connect(self.add_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 130, 101, 22))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.stateChanged.connect(self.add_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 160, 101, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.stateChanged.connect(self.add_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 190, 101, 22))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_4.stateChanged.connect(self.add_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 220, 101, 22))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_5.stateChanged.connect(self.add_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 250, 101, 22))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_6.stateChanged.connect(self.add_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(30, 280, 131, 22))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_7.stateChanged.connect(self.add_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(30, 310, 131, 22))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_8.stateChanged.connect(self.add_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(30, 340, 131, 22))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_9.stateChanged.connect(self.add_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(30, 370, 131, 22))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_10.stateChanged.connect(self.add_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(30, 400, 131, 22))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_11.stateChanged.connect(self.add_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(30, 430, 131, 22))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_12.stateChanged.connect(self.add_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_13.setGeometry(QtCore.QRect(30, 460, 131, 22))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_13.stateChanged.connect(self.add_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_14.setGeometry(QtCore.QRect(30, 490, 131, 22))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_14.stateChanged.connect(self.add_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_15.setGeometry(QtCore.QRect(170, 100, 131, 22))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_15.stateChanged.connect(self.add_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_16.setGeometry(QtCore.QRect(170, 130, 141, 22))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_16.stateChanged.connect(self.add_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_17.setGeometry(QtCore.QRect(170, 160, 151, 22))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_17.stateChanged.connect(self.add_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_18.setGeometry(QtCore.QRect(170, 190, 101, 22))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_18.stateChanged.connect(self.add_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_19.setGeometry(QtCore.QRect(170, 220, 131, 22))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_19.stateChanged.connect(self.add_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_20.setGeometry(QtCore.QRect(170, 250, 131, 22))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_20.stateChanged.connect(self.add_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_21.setGeometry(QtCore.QRect(170, 280, 101, 22))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_21.stateChanged.connect(self.add_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_22.setGeometry(QtCore.QRect(170, 310, 101, 22))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_22.stateChanged.connect(self.add_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_23.setGeometry(QtCore.QRect(170, 340, 101, 22))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_23.stateChanged.connect(self.add_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_24.setGeometry(QtCore.QRect(170, 370, 131, 22))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_24.stateChanged.connect(self.add_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_25.setGeometry(QtCore.QRect(170, 400, 121, 22))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_25.stateChanged.connect(self.add_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_26.setGeometry(QtCore.QRect(170, 430, 131, 22))
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_26.stateChanged.connect(self.add_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_27.setGeometry(QtCore.QRect(170, 460, 131, 22))
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_27.stateChanged.connect(self.add_27)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(440, 100, 151, 27))
        self.comboBox.setObjectName("comboBox")        

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 180, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(440, 240, 141, 27))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 300, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(660, 352, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        self.pathPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pathPushButton.setGeometry(QtCore.QRect(430, 350, 97, 27))
        self.pathPushButton.setObjectName("pathPushButton")
        self.pathPushButton.clicked.connect(self.path_button_push)

        self.updatePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.updatePushButton.setGeometry(QtCore.QRect(540, 350, 97, 27))
        self.updatePushButton.setObjectName("updatePushButton")
        self.updatePushButton.clicked.connect(self.update_button_push)

        self.allPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.allPushButton.setGeometry(QtCore.QRect(30, 550, 97, 27))
        self.allPushButton.setObjectName("allPushButton")
        self.allPushButton.clicked.connect(self.all_button_push)

        self.allnotPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.allnotPushButton.setGeometry(QtCore.QRect(170, 550, 97, 27))
        self.allnotPushButton.setObjectName("allnotPushButton")
        self.allnotPushButton.clicked.connect(self.all_not_button_push)

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(430, 390, 300, 192))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setReadOnly(True)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "億載金城"))
        self.checkBox_2.setText(_translate("MainWindow", "安平樹屋"))
        self.checkBox_3.setText(_translate("MainWindow", "林默娘公園"))
        self.checkBox_4.setText(_translate("MainWindow", "安平老街"))
        self.checkBox_5.setText(_translate("MainWindow", "安平古堡"))
        self.checkBox_6.setText(_translate("MainWindow", "東興洋行"))
        self.checkBox_7.setText(_translate("MainWindow", "安平開臺天后宮"))
        self.checkBox_8.setText(_translate("MainWindow", "安平遊憩碼頭"))
        self.checkBox_9.setText(_translate("MainWindow", "台南公園"))
        self.checkBox_10.setText(_translate("MainWindow", "花園夜市"))
        self.checkBox_11.setText(_translate("MainWindow", "開元寺"))
        self.checkBox_12.setText(_translate("MainWindow", "321巷藝術聚落"))
        self.checkBox_13.setText(_translate("MainWindow", "祀典武廟"))
        self.checkBox_14.setText(_translate("MainWindow", "台灣文學館"))
        self.checkBox_15.setText(_translate("MainWindow", "巴克禮公園"))
        self.checkBox_16.setText(_translate("MainWindow", "藍曬圖文創園區"))
        self.checkBox_17.setText(_translate("MainWindow", "原台南縣知事官邸"))
        self.checkBox_18.setText(_translate("MainWindow", "神農街"))
        self.checkBox_19.setText(_translate("MainWindow", "台南文創園區"))
        self.checkBox_20.setText(_translate("MainWindow", "台南火車站"))
        self.checkBox_21.setText(_translate("MainWindow", "大天后宮"))
        self.checkBox_22.setText(_translate("MainWindow", "赤崁樓"))
        self.checkBox_23.setText(_translate("MainWindow", "林百貨"))
        self.checkBox_24.setText(_translate("MainWindow", "延平郡王祠"))
        self.checkBox_25.setText(_translate("MainWindow", "海安路藝術街"))
        self.checkBox_26.setText(_translate("MainWindow", "成大榕園"))
        self.checkBox_27.setText(_translate("MainWindow", "孔廟"))
        self.label.setText(_translate("MainWindow", "1. 選擇欲前往地標"))
        self.label_2.setText(_translate("MainWindow", "2. 選擇起點(終點)"))
        self.label_3.setText(_translate("MainWindow", "3.選擇交通工具"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "大眾運輸"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "開車"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "走路"))
        self.label_4.setText(_translate("MainWindow", "4.輸出路徑！"))
        self.label_5.setText(_translate("MainWindow", ""))
        self.pathPushButton.setText(_translate("MainWindow", "輸出"))
        self.updatePushButton.setText(_translate("MainWindow", "更新資料"))
        self.allPushButton.setText(_translate("MainWindow", "全選"))
        self.allnotPushButton.setText(_translate("MainWindow", "全不選"))
        self.textEdit.setText(_translate("MainWindow", ""))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

